### ISSUE TITLE
TypeScript types?

### ISSUE THREAD

**Issue by Shadofer** [shiryel/saos#10]
Wondering if anyone has taken the initiative to create types for this package?

I have no problem trying it myself if I am able to adjust the general structure.

**Comment by shiryel** [comment]
I don't think anyone took that initiative yet, but feel free to send a PR, I'll gladly welcome it :+1:

**Comment by Shadofer** [comment]
I'll try my best :+1:

**Comment by Shadofer** [comment]
Actually, the only viable source I could find is https://kit.svelte.dev/docs/packaging

**Comment by shiryel** [comment]
As this lib is just a small component, maybe it would help to try to generate and configure a pure svelte code-base to see what is necessary to make one typed.

**Comment by Shadofer** [comment]
`SvelteComponentTyped` worked for me [here](https://github.com/Fronvo/site/blob/master/src/saos.d.ts) but I'm not sure how that translates to publishing.

**Comment by shiryel** [comment]
You should try something like the `index.d.ts` here: https://github.com/beyonk-adventures/svelte-notifications/tree/master/src/lib

I think you can test modifying saos inside your node_modules, but I'm not sure.

**Comment by Shadofer** [comment]
https://github.com/shiryel/saos/pull/11

**Comment by Shadofer** [comment]
https://github.com/shiryel/saos/pull/11
