### ISSUE TITLE
Vulnerable version of Axios

### ISSUE THREAD

**Issue by xkjay** [shiryel/saos#23]
# The version of Axios that is in the deps tree, is vulnerable. (at least on NPM)
### Issues:
Exposure of Sensitive Information to an Unauthorized Actor in follow-redirects - https://github.com/advisories/GHSA-pw2r-vq6v-hr8c
Exposure of sensitive information in follow-redirects - https://github.com/advisories/GHSA-74fj-2j2h-c42q
## Please fix this, as simply upgrading Axios should fix it.
Given that there is not a security policy, I am resorted to open an issue. I would recommend adding one, so maybe consider doing that.

**Comment by shiryel** [comment]
Could you specify which dependency is using Axios? Thanks

Also, should not be a problem as this package does not use any dependency to work, we only have dev dependencies.
